= Docker
:awestruct-layout: solution-detail

== Overview
The Docker project revolutionizes thinking about software delivery making it easy to build and share images that include your content. 
We at JBoss love the idea behind Docker and ship images for our projects. 
Just for you.

=== JBoss projects and Docker

We publish our images under the official jboss organization. 
Every image is built from Dockerfiles available in our GitHub repository. 
To keep them up to date we have automated builds that track the source and rebuild images (only) if necessary. 
Additionally, images are linked to each other: If an image we’re base on is modified, we rebuild our image to provide you the fresh image that you deserve.

== Left Section

=== Goal
We provide Docker images for our JBoss projects to let you focus on using them instead of worrying about packaging.
The Docker image delivery format makes it easy to extend/reuse images. It is a good idea to use our images as the base for your own image (using the FROM command in your Dockerfile).

=== Issues and enhancements
If you have issues with images listed below or you have an idea on how to make them better please open a new ticket. 
Please start the ticket name with a [image-name] prefix, eg. [jboss/wildfly].

== Right Section

=== Documentation
Every image is different therefore please consult the readme linked to each image. If you don’t find the answer there, don’t hesitate to contact us.

=== Contact
We’re there for you on IRC in the #jboss-docker channel on Freenode.
